import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Lexend_Giga } from "next/font/google";
import "./globals.css";

const lexendGiga = Lexend_Giga({
  weight: ["400", "600", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

const roboto = Roboto({
  weight: ["200", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${lexendGiga.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
